apiVersion: v1
kind: Service
metadata:
  name: dart-task01-service
  labels:
    app: dart
spec:
  type: NodePort
  selector:
    app: dart
  ports:
    - nodePort: 30000
      protocol: TCP
      port: 8080
      targetPort: 5000